from pathlib import Path


PERSIST_DIRECTORY = str(Path(__file__).resolve().parents[1] / "data" / "chroma")
COLLECTION_NAME = "test_case_rag_v1"
EMBEDDING_MODEL = "text-embedding-3-small"
LOCAL_EMBEDDING_DIM = 256

CHUNK_SIZE = 500
CHUNK_OVERLAP = 80

RETRIEVER_TOP_K = 8
FETCH_K = 20
SEARCH_TYPE = "mmr"
HYBRID_SEARCH_ENABLED = True
BM25_TOP_K = 8
RRF_K = 60

MULTI_QUERY_ENABLED = True
QUERY_COUNT = 3
PER_QUERY_TOP_K = 3

ENABLE_RERANK = True
RERANK_MODE = "cross_encoder"
RERANK_CROSS_ENCODER_MODEL = "BAAI/bge-reranker-v2-m3"
RERANK_CROSS_ENCODER_LOCAL_FILES_ONLY = True
RERANK_TIMEOUT_MS = 30000
RERANK_CANDIDATE_POOL = 12
RERANK_FINAL_TOP_N = 5

MAX_CONTEXT_CHARS = 6000
